# Generated by Django 5.2.6 on 2025-11-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='text',
            new_name='conteudo',
        ),
    ]
