# Generated by Django 5.2.6 on 2025-11-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_text_posts_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='conteudo',
            field=models.TextField(max_length=2048),
        ),
    ]
