# Generated by Django 5.2.6 on 2025-11-21 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
