# Generated by Django 5.2.6 on 2025-11-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='conteudo',
            field=models.TextField(max_length=4096),
        ),
    ]
