# Generated by Django 5.2.6 on 2025-11-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posts_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='posts',
            name='conteudo',
            field=models.TextField(max_length=2048),
        ),
        migrations.AddField(
            model_name='posts',
            name='categorias',
            field=models.ManyToManyField(related_name='posts', to='posts.categoria'),
        ),
    ]
