# Generated by Django 5.2.6 on 2025-11-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_categoria_remove_posts_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
