# Generated by Django 5.2.6 on 2025-11-23 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posts_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='likes',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
